### ISSUE TITLE
Windows 10 build - COPY Failed at step 7/16 

### ISSUE THREAD

**Issue by brandoncaulfield** [tobiashofmann/sap-nw-abap-docker#14]
Hi @tobiashofmann,

I'm sure this is as illy mistake but when I run the build command I get the error below: 
```
Sending build context to Docker daemon  29.42GB
Step 1/16 : FROM opensuse/archive:latest
 ---> d9e50bf28896
Step 2/16 : LABEL de.itsfullofstars.sapnwdocker.version="1.0.0"
 ---> Using cache
 ---> 4df71ee90ee5
Step 3/16 : LABEL de.itsfullofstars.sapnwdocker.vendor="Tobias Hofmann"
 ---> Using cache
 ---> 6c554e2e7fe8
Step 4/16 : LABEL de.itsfullofstars.sapnwdocker.name="Docker for SAP NetWeaver 7.5x Developer Edition"
 ---> Using cache
 ---> dfe360a620f4
Step 5/16 : RUN zypper --non-interactive install --replacefiles uuidd expect tcsh which vim hostname tar net-tools iputils libaio iproute2 gzip;     zypper clean
 ---> Using cache
 ---> d79af233ddfd
Step 6/16 : RUN mkdir /run/uuidd && chown uuidd /var/run/uuidd && /usr/sbin/uuidd
 ---> Using cache
 ---> 5b5e9d6aab58
Step 7/16 : COPY NW752 /var/tmp/NW752/
COPY failed: stat /var/lib/docker/tmp/docker-builder543000156/NW752: no such file or directory
```
I believe I've followed all the instructions correctly including having the docker file in the same directory as the extracted SAP files.

Any idea where I've gone wrong? (Trying in windows 10)

Thanks!
B

**Comment by amo42** [comment]
Hi @brandoncaulfield  I'm not a windows user, but docker seams to search the downloaded files within the wrong directory:

/var/lib/docker/tmp/docker-builder543000156/NW752

Not sure how docker runs on Windows but can you try to change the COPY command (line 16 of Dockerfile) to this:

`COPY ./NW752 /var/tmp/NW752/`

In addition could you provide a screenshot of the directory structure, just to ensure everything is fine.

Best
Andreas

**Comment by brandoncaulfield** [comment]
Thanks @amo42! I've realised I need to brush up on my docker folder system in Windows specifically. This didnt exactly work but it lead me to the correct path to fix it. Thanks!

**Comment by belezyc** [comment]
> Hi @brandoncaulfield I'm not a windows user, but docker seams to search the downloaded files within the wrong directory:
> 
> /var/lib/docker/tmp/docker-builder543000156/NW752
> 
> Not sure how docker runs on Windows but can you try to change the COPY command (line 16 of Dockerfile) to this:
> 
> `COPY ./NW752 /var/tmp/NW752/`
> 
> In addition could you provide a screenshot of the directory structure, just to ensure everything is fine.
> 
> Best
> Andreas

Adding reference to local directory for docker host source path solved the problem for me. Thank you!

KR,
Clément

**Comment by brandoncaulfield** [comment]
Hi @belezyc I managed to get it working and created a docker file in this repo specific to windows [here](https://github.com/brandoncaulfield/sap-nw-abap-trial-docker-windows) 🙂
