### ISSUE TITLE
issue while docker build

### ISSUE THREAD

**Issue by yashpal8** [tobiashofmann/sap-nw-abap-docker#3]
Hi ,
after running code
docker build -t nwabap .

i am getting below in command prompt

Step 15/15 : RUN ./run.sh
 ---> Running in 40ddce4e4402
spawn ./install.sh -s -k
Hostname check skipped!
Hit enter to continue!

if i hit enter nothing happens then i did ctrl+c which ends the thing and i am not able to run below command
docker run -P -h vhcalnplci --name nwabap752 -it nwabap:latest /bin/bash

can you help here ?
Thanks
Yashpal

**Comment by spvi1011** [comment]
Same for me, is there a solution for this issue?

Thanks and best regards,
Viktor

**Comment by furlan** [comment]
You should use NW7.52 version. I believe you're using an old version. Previous versions of instalation  you need to hit ENTER until the end of EULA. On NW7.52 you don't need to go to until the end of EULA to accept.

Another solution (ugly one) is to comment out ./run.sh from the Dockfile and execute instalation manually after Container creation.
