### ISSUE TITLE
modlib.jslib.caughtException during ./install.sh -s -k

### ISSUE THREAD

**Issue by stefan12555** [tobiashofmann/sap-nw-abap-docker#4]
Hi,

i got the the same problem with ./run.sh, that "enter" will not continue installation. So I tried to execute ./install.sh -s -k direct, but i also get some trouble there. 

...
a /tmp/sapinst_instdir/NW73/SBC/STANDARD/start_dir.cd
a /tmp/sapinst_instdir/NW73/SBC/STANDARD/stepKeydbClient.dmp
a /tmp/sapinst_instdir/NW73/SBC/STANDARD/syslib_priv.log
################################################
Abort execution because of 
Step returns modlib.jslib.caughtException
################################################

INFO       2018-09-30 14:52:10.043 (root/sapinst) (startInstallation) [syuxcdir.cpp:147] id=syslib.filesystem.removedDirectory CSyDirectoryImpl::sap_remove(ISyFSErrorHandler * pErrorHandler)
Removed directory /root/.sapinst/vhcalnplci/262.

Error: sapinst has finished with an error code, please find logs in /tmp/sapinst_instdir
All logs have been written to the file /tmp/NW752/install_2018-09-30_14-50-53.log
Please see readme.html to find out how to get help
*******

Here is the log file

vhcalnplci:/tmp/NW752 # vi install_2018-09-30_14-50-53.log 

Script version: c95e4ee99a5b9ca25fc1d4d872bdc0b9 /tmp/NW752/install.sh
Found files from previous installation, please clean up if you want to run a
new installation! Otherwise, we just overwrite /sapmnt/NPL directory, so that
you can safely resume the installation
Running on tested distribution opensuse
To install this TestDrive you have to accept
the SAP COMMUNITY DEVELOPER License (DEV).
Do you agree to the above license terms? yes/no:
User's response to the accept license prompt = 'yes'
Please enter a password:
Please re-enter password for verification:
extracting data archives...
extracting /tmp/NW752/server/TAR/x86_64/sapmnt.tgz-*
Kernel parameters not set!
Checking presence of new SYBASE license file
Updated the license file /sybase/NPL/SYSAM-2_0/licenses
Install service
Check Installation Path ...
ok
Copy Executable ...
ok
Generate Profile ...
ok
Install SYS-V service ...
ok
-> Start /usr/sap/hostctrl/exe/saphostexec pf=/usr/sap/hostctrl/exe/host_profile <-
start hostcontrol using profile /usr/sap/hostctrl/exe/host_profile
ok
[OK] SAPHostExec / SAPHostControl succesfully installed
Executing: "/usr/sap/hostctrl/exe/SAPCAR" -xvf "./SHADBMETRICSDEF.SAR" -R "/usr/sap/hostctrl/exe/config.d"
SAPCAR: processing archive ./SHADBMETRICSDEF.SAR (version 2.01)
x dbmetric.definition.db4.cimobj
x dbmetric.definition.db6.cimobj
x dbmetric.definition.hdb.cimobj
x dbmetric.definition.mss.cimobj
x dbmetric.definition.ora.cimobj
x dbmetric.definition.sap.cimobj
x dbmetric.definition.siq.cimobj
x dbmetric.definition.syb.cimobj
x dbmetric.definition.tst.cimobj
x dbmetrics.d
x dbmetrics.d/00.general.hdb.cimobj
x dbmetrics.d/00.state.hdb.cimobj
x dbmetrics.d/10.host.capacity.hdb.cimobj
x dbmetrics.d/20.indexserver.hdb.cimobj
x dbmetrics.d/20.nameserver.hdb.cimobj
SAPCAR: 15 file(s) extracted
SAPCAR: rc 0
=>sapparam(1c): No Profile used.
=>sapparam: SAPSYSTEMNAME neither in Profile nor in Commandline
################################################
Abort execution because of
Step returns modlib.jslib.caughtException
################################################
Error: sapinst has finished with an error code, please find logs in /tmp/sapinst_instdir
Error code: 20
++++ Support data section BEGIN ++++
* mount
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/EHLQ36766ARHC77VZ2WQXMHNIM:/var/lib/docker/overlay2/l/HV2O6ICWHI7YM7J77YGGJP5JDM:/var/lib/docker/overlay2/l/AIHF6VTM4LQ2RMU5ZYFULQK57J:/var/lib/docker/overlay2/l/LKWROMOFKGAOLZYUBOW43GTFJK:/var/lib/docker/overlay2/l/QHSFSB2WNEJ7P4PDDSQAB5DEWZ:/var/lib/docker/overlay2/l/NCEF6FIDWA2LYJRI7QB4VGIM25:/var/lib/docker/overlay2/l/LVVITFZP7Y4F3JFTVKBAUERROY:/var/lib/docker/overlay2/l/GQSVUGBEMS3KHKEP4EFKEGYVF2,upperdir=/var/lib/docker/overlay2/61e3f0b69c8218365a383108f1d83981bf84fda244f8d0bc8b8e7cea5467da37/diff,workdir=/var/lib/docker/overlay2/61e3f0b69c8218365a383108f1d83981bf84fda244f8d0bc8b8e7cea5467da37/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
/dev/sda2 on /etc/resolv.conf type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda2 on /etc/hostname type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda2 on /etc/hosts type ext4 (rw,relatime,errors=remount-ro,data=ordered)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
proc on /proc/asound type proc (ro,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime)
tmpfs on /sys/firmware type tmpfs (ro,relatime)
* df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         219G   94G  115G  45% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sda2       219G   94G  115G  45% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G   0% /sys/firmware
* df -hi
Filesystem     Inodes IUsed IFree IUse% Mounted on
overlay           14M  251K   14M    2% /
tmpfs            4.0M    17  4.0M    1% /dev
tmpfs            4.0M    17  4.0M    1% /sys/fs/cgroup
/dev/sda2         14M  251K   14M    2% /etc/hosts
shm              4.0M     1  4.0M    1% /dev/shm
tmpfs            4.0M     1  4.0M    1% /proc/scsi
tmpfs            4.0M     1  4.0M    1% /sys/firmware
* cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.3"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.3"
PRETTY_NAME="openSUSE Leap 42.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
* ls -ld / /sybase /usr/sap /sapmnt
drwxr-xr-x 1 root   root   4096 Sep 30 14:50 /
drwxr-xr-x 1 root   root   4096 Jul 17 13:26 /sapmnt
drwxr-x--- 1 sybnpl sapsys 4096 Feb 20  2017 /sybase
drwxr-xr-x 1 root   root   4096 Sep 30 14:37 /usr/sap
++++ Support data section END ++++
All logs have been written to the file /tmp/NW752/install_2018-09-30_14-50-53.log
Please see readme.html to find out how to get help

Maybe you can help. Would be very nice.

Thx Stefan

**Comment by stefan12555** [comment]
fixed by my own

**Comment by saidani91** [comment]
Can you please share how did you solve this 
Thanks

**Comment by stefan12555** [comment]
Hi, will check. Can’t remember for now. If i remember correct, i changed in the install.sh. Removed the place, where the script stops.

**Comment by saidani91** [comment]
It was a license issue for me I generated it into file NPL.txt
then during install opened new prompt ( docker exec -it <container name> /bin/bash ) : 

vhcalnplci:/tmp/sapdownloads #  cp NPL.tx /sybase/NPL/SYSAM-2_0/licenses/SYBASE_ASE_TestDrive.lic
vhcalnplci:/sybase/NPL # cd /sybase/NPL/SYSAM-2_0/licenses
vhcalnplci:/sybase/NPL/SYSAM-2_0/licenses # chmod 0750 SYBASE_ASE_TestDrive.lic
vhcalnplci:/sybase/NPL/SYSAM-2_0/licenses # chown sybnpl:sapsys SYBASE_ASE_TestDrive.lic

**Comment by reline772** [comment]
> 
> 
> Hi, will check. Can’t remember for now. If i remember correct, i changed in the install.sh. Removed the place, where the script stops.

Hallo i Have The same problem with the instalation of NLP Please kann you tell me what exactly you remove from your Install.sh Script? 
please a need your help.

Tkx
