### ISSUE TITLE
run.sh missing

### ISSUE THREAD

**Issue by NLstn** [tobiashofmann/sap-nw-abap-docker#7]
Hi, 

I did follow your instructions on how to generate the docker image. After starting the instance, i am located in folder /var/tmp/NW752, which doesn't really exists anymore by this point. I cannot find the run.sh script in the container, can you help me out?

**Comment by drumminganna** [comment]
Hi guys, I have the same problem. Want to execute the run.sh file but its not there. Can someone help me? Regards
